//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotSpots {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotSpots.UserResources", typeof(UserResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
        ///
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///    var _csv = {};
        ///    _csv[&apos;action_target&apos;] = &apos;{listing_profile}&apos;;
        ///    _csv[&apos;listing_id&apos;] = &apos;{listing_id}&apos;;
        ///    _csv[&apos;publisher&apos;] = &apos;{publisher}&apos;;
        ///    _csv[&apos;reference_id&apos;] = &apos;{reference_id}&apos;;
        ///    _csv[&apos;mobile_type&apos;] = &apos;wp7&apos;;
        ///    _csv[&apos;muid&apos;] = &apos;{muid}&apos;;
        /// &lt;/script&gt;
        ///&lt;script type=&quot;text/javascript&quot; src=&quot;http://api.citygridmedia.com/ads/tracker/assets/api/scripts/tracker.js&quot;&gt;&lt;/script&gt;
        ///&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImpressionTracker {
            get {
                return ResourceManager.GetString("ImpressionTracker", resourceCulture);
            }
        }
    }
}
